# Generated by Django 2.1.7 on 2019-03-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=200)),
                ('vendorname', models.CharField(db_index=True, max_length=200)),
                ('joiningdate', models.DateField(auto_now_add=True)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('vendorcontact', models.CharField(db_index=True, max_length=14)),
                ('payamount', models.CharField(db_index=True, max_length=200)),
                ('totalamount', models.CharField(db_index=True, max_length=200)),
                ('total_due', models.CharField(db_index=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(db_index=True, max_length=200)),
                ('milkprice', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vendorledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milktype', models.CharField(db_index=True, max_length=200)),
                ('vendorname', models.CharField(db_index=True, max_length=200)),
                ('managername', models.CharField(db_index=True, max_length=200)),
                ('day', models.CharField(db_index=True, max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.CharField(db_index=True, max_length=200)),
                ('total', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
