# Generated by Django 2.1.7 on 2019-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_animalcategory_related_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorledger',
            name='milktype',
        ),
    ]
