# Generated by Django 2.1.7 on 2019-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_auto_20190303_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvendor',
            name='payamount',
            field=models.FloatField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='addvendor',
            name='total_due',
            field=models.FloatField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='addvendor',
            name='totalamount',
            field=models.FloatField(db_index=True, default=0.0, max_length=200),
        ),
    ]
