# Generated by Django 2.1.7 on 2019-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0008_auto_20190303_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='payamount',
            field=models.FloatField(db_index=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_due',
            field=models.FloatField(db_index=True, default=0.0, max_length=200),
        ),
    ]
