# Generated by Django 2.1.7 on 2019-03-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0009_auto_20190303_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='payamount',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='total_due',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='totalamount',
        ),
    ]
