# Generated by Django 2.1.7 on 2019-03-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0010_auto_20190303_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorledger',
            name='managername',
        ),
        migrations.RemoveField(
            model_name='vendorledger',
            name='vendorname',
        ),
        migrations.AddField(
            model_name='vendorledger',
            name='related_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorledger', to='dairyapp.Vendor'),
        ),
        migrations.AlterField(
            model_name='milkcategory',
            name='animalname',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Others', 'Others')], max_length=200),
        ),
    ]
