# Generated by Django 2.0.13 on 2020-05-19 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyapp', '0012_vendorledger_related_milkcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=1000000)),
                ('price', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('quantity', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('total', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMilkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Others', 'Others')], max_length=200)),
                ('milkprice', models.FloatField(db_index=True, max_length=200)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerMilkCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Manager', 'Manager')], max_length=20, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True, unique=True)),
                ('joining_data', models.DateField()),
                ('address', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user_type',),
            },
        ),
        migrations.AlterModelOptions(
            name='vendorledger',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='vendorledger',
            name='day',
        ),
        migrations.AlterField(
            model_name='milkcategory',
            name='milkprice',
            field=models.FloatField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='date',
            field=models.CharField(db_index=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='price',
            field=models.FloatField(db_index=True, default=0.0, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='quantity',
            field=models.FloatField(db_index=True, default=0.0, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='total',
            field=models.FloatField(db_index=True, default=0.0, max_length=1000000),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='related_milk_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to='dairyapp.CustomerMilkCategory'),
        ),
    ]
