# Generated by Django 2.1.7 on 2019-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0013_remove_vendorledger_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorledger',
            name='price',
            field=models.CharField(db_index=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='quantity',
            field=models.CharField(db_index=True, default=0, max_length=200),
        ),
    ]
