# Generated by Django 2.1.7 on 2019-03-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0014_auto_20190305_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorledger',
            name='price',
            field=models.FloatField(db_index=True, default=0.0, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='quantity',
            field=models.FloatField(db_index=True, default=0, max_length=1000000),
        ),
    ]
