# Generated by Django 2.1.7 on 2019-03-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0017_auto_20190308_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorledger',
            name='day',
        ),
    ]
