# Generated by Django 2.1.7 on 2019-03-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0018_remove_vendorledger_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorledger',
            name='total',
            field=models.FloatField(db_index=True, default=0.0, max_length=1000000),
        ),
    ]
