# Generated by Django 2.1.7 on 2019-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0019_vendorledger_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcategory',
            name='milkprice',
            field=models.FloatField(db_index=True, max_length=200),
        ),
    ]
