# Generated by Django 2.1.7 on 2019-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0020_auto_20190308_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorledger',
            name='date',
            field=models.CharField(db_index=True, max_length=1000000),
        ),
    ]
