# Generated by Django 2.1.7 on 2019-03-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0021_auto_20190308_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorledger',
            options={'ordering': ('date',)},
        ),
    ]
