# Generated by Django 2.1.7 on 2019-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0022_auto_20190308_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorledger',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='vendorledger',
            name='quantity',
            field=models.FloatField(db_index=True, default=1.0, max_length=1000000),
        ),
    ]
