# Generated by Django 2.1.7 on 2019-03-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0023_auto_20190312_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorledger',
            name='quantity',
            field=models.FloatField(db_index=True, default=0.0, max_length=1000000),
        ),
    ]
