# Generated by Django 2.1.7 on 2019-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0025_auto_20190320_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
