# Generated by Django 2.1.7 on 2019-03-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0026_auto_20190320_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
