# Generated by Django 2.1.7 on 2019-03-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0027_remove_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
