# Generated by Django 2.1.7 on 2019-03-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0028_auto_20190320_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
