# Generated by Django 2.1.7 on 2019-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0031_auto_20190320_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('mobile_number', models.IntegerField(db_index=True, max_length=1000)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('is_customer', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
