# Generated by Django 2.1.7 on 2019-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0038_auto_20190322_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Manager', 'Manager')], max_length=20, null=True),
        ),
    ]
