# Generated by Django 2.1.7 on 2019-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0039_auto_20190322_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Manager', 'Manager')], max_length=20, null=True),
        ),
    ]
