# Generated by Django 2.1.7 on 2019-03-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0042_auto_20190322_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
