# Generated by Django 2.1.7 on 2019-03-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0043_auto_20190322_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
