# Generated by Django 2.1.7 on 2019-03-23 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyapp', '0044_auto_20190322_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMilkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Others', 'Others')], max_length=200)),
                ('milkprice', models.FloatField(db_index=True, max_length=200)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerMilkCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
