# Generated by Django 2.1.7 on 2019-03-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0047_auto_20190324_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=1000000)),
                ('price', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('quantity', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('total', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('milkcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to='dairyapp.CustomerMilkCategory')),
            ],
        ),
    ]
