# Generated by Django 2.1.7 on 2019-04-02 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyapp', '0048_customerledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledger',
            name='milkcategory',
        ),
        migrations.AddField(
            model_name='customerledger',
            name='related_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to=settings.AUTH_USER_MODEL),
        ),
    ]
