# Generated by Django 2.1.7 on 2019-04-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0049_auto_20190402_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='related_milk_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to='dairyapp.CustomerMilkCategory'),
        ),
    ]
